version: "3"

services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/app
    environment:
      WAIT_HOSTS: mongo:27017

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db